version: '3.9'

services:
  db:
    image: mysql
    restart: always
    environment:
      TZ: American/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker_from_zero_to_mastery_java
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: true
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - erudio-network

  docker-from-zero-to-mastery-java:
    image: docker-from-zero-to-mastery-java
    container_name: docker-from-zero-to-mastery-java
    restart: always
    build: ./app
    working_dir: /app
    environment:
      TZ: American/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/docker_from_zero_to_mastery_java?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: docker
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erudio-network
networks:
  erudio-network:
    driver: bridge
